### ISSUE TITLE
rixens-esphome esp hardware example request

### ISSUE THREAD

**Issue by neckermann** [mikegoubeaux/rixens-esphome#2]
Awesome write up. I am super new to HA and ESP, but as I am building my van I thought why not go all in with all the fun stuff. 

I was wondering if you can add to your readme an example of your hardware layout.

**Comment by mikegoubeaux** [comment]
Which hardware are you referring to? All of the Rixen's system is documented on their site. And the pinout for can bus is in issue #1

**Comment by neckermann** [comment]
Sorry I could have been more specific. 
What I mean is the hardware that you are plugging into the can bus connection on the rixens controller. 
I assume esp32 (any one specifically) and a can bus sending unit (any one specifically) connected to it etc.

**Comment by mikegoubeaux** [comment]
Have you read the link to the ESPHome [can bus](https://esphome.io/components/canbus.html#esp32-can-component) documentation in my writeup? I think that should get you what you need. But, yes, esp32 is the easiest as there is an onboard can bus controller, you just have to define which GPIO pins you are using for can H and can L. But, you'll need to provide power to your board somehow (which is 5v via usb or other input methods depending on the board). I am using a custom board with 12v power input so that it can easily be powered off of the Rixen's board as they provide 12v and can on that one header.

I'm using something similar to this [development board](https://copperhilltech.com/esp32-wifi-bluetooth-classic-ble-can-bus-module/) that has 12v step down and can bus headers all built in - which is pretty nice. That way you can just bury the little board inside the Rixen's control box.

Hope that helps!

**Comment by neckermann** [comment]
That's great! Thank you.

**Comment by neckermann** [comment]
That's great! Thank you.
